language: java
jdk:
- openjdk7

services:
- mysql

before_script:
 - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'
 
deploy:
  provider: heroku
  api-key:  
     secure: "8baccd35-fa09-4d88-ae57-0d34b0bfcbca" 
  app: rigo2   
