language: java
jdk:
- openjdk7

services:
- mysql

before_script:
 - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'
 - mysql -u root -e 'USE test; create table USERS (USERNAME VARCHAR(10),FIRSTNAME VARCHAR(30),SECONDNAME VARCHAR(30), PRIMARY KEY(USERNAME));'
 - mysql -u root -e "USE test; insert into USERS(USERNAME,FIRSTNAME,SECONDNAME) values ('DMENDIVIL','DOMINGO','MENDIVIL');"
 
  
 
deploy:
  provider: heroku
  api-key:  
     secure: "8baccd35-fa09-4d88-ae57-0d34b0bfcbca" 
  app: rigo2   
  run: "mysql -u bc32713433d1de -p 31b94f6c -e 'CREATE DATABASE IF NOT EXISTS test;'"
